package com.appointment.api.handler.address;

import com.appointment.api.handler.Handler;
import org.springframework.stereotype.Component;

import java.util.LinkedList;
import java.util.List;

@Component
public class AddressMapHandler implements Handler<String, String> {

    @Override
    public String execute(String request) {
        return request;
    }

    private void Countries(){
        List<String[]> countryList=new LinkedList<>();
        countryList.add(new String[]{"AF", "AFG", "Afghanistan", "93"});
        countryList.add(new String[]{"AL", "ALB", "Albania", "355"});
        countryList.add(new String[]{"DZ", "DZA", "Algeria", "213"});
        countryList.add(new String[]{"AS", "ASM", "American Samoa", "684"});
        countryList.add(new String[]{"AD", "AND", "Andorra", "376"});
        countryList.add(new String[]{"AO", "AGO", "Angola", "244"});
        countryList.add(new String[]{"AI", "AIA", "Anguilla", "264"});
        countryList.add(new String[]{"AQ", "ATA", "Antarctica", "672"});
        countryList.add(new String[]{"AG", "ATG", "Antigua and Barbuda", "268"});
        countryList.add(new String[]{"AR", "ARG", "Argentina", "54"});
        countryList.add(new String[]{"AM", "ARM", "Armenia", "374"});
        countryList.add(new String[]{"AW", "ABW", "Aruba", "297"});
        countryList.add(new String[]{"AU", "AUS", "Australia", "61"});
        countryList.add(new String[]{"AT", "AUT", "Austria", "43"});
        countryList.add(new String[]{"AZ", "AZE", "Azerbaijan", "994"});
        countryList.add(new String[]{"BS", "BHS", "Bahamas", "242"});
        countryList.add(new String[]{"BH", "BHR", "Bahrain", "973"});
        countryList.add(new String[]{"BD", "BGD", "Bangladesh", "880"});
        countryList.add(new String[]{"BB", "BRB", "Barbados", "246"});
        countryList.add(new String[]{"BY", "BLR", "Belarus", "375"});
        countryList.add(new String[]{"BE", "BEL", "Belgium", "32"});
        countryList.add(new String[]{"BZ", "BLZ", "Belize", "501"});
        countryList.add(new String[]{"BJ", "BEN", "Benin", "229"});
        countryList.add(new String[]{"BM", "BMU", "Bermuda", "441"});
        countryList.add(new String[]{"BT", "BTN", "Bhutan", "975"});
        countryList.add(new String[]{"BO", "BOL", "Bolivia", "591"});
        countryList.add(new String[]{"BA", "BIH", "Bosnia and Herzegovina", "387"});
        countryList.add(new String[]{"BW", "BWA", "Botswana", "267"});
        countryList.add(new String[]{"BR", "BRA", "Brazil", "55"});
        countryList.add(new String[]{"VG", "VGB", "British Virgin Islands", "284"});
        countryList.add(new String[]{"BN", "BRN", "Brunei", "673"});
        countryList.add(new String[]{"BG", "BGR", "Bulgaria", "359"});
        countryList.add(new String[]{"BF", "BFA", "Burkina Faso", "226"});
        countryList.add(new String[]{"BI", "BDI", "Burundi", "257"});
        countryList.add(new String[]{"KH", "KHM", "Cambodia", "855"});
        countryList.add(new String[]{"CM", "CMR", "Cameroon", "237"});
        countryList.add(new String[]{"CA", "CAN", "Canada", "1"});
        countryList.add(new String[]{"CV", "CPV", "Cape Verde", "238"});
        countryList.add(new String[]{"KY", "CYM", "Cayman Islands", "345"});
        countryList.add(new String[]{"CF", "CAF", "Central African Republic", "236"});
        countryList.add(new String[]{"TD", "TCD", "Chad", "235"});
        countryList.add(new String[]{"CL", "CHL", "Chile", "56"});
        countryList.add(new String[]{"CN", "CHN", "China", "86"});
        countryList.add(new String[]{"CX", "CXR", "Christmas Island", "61"});
        countryList.add(new String[]{"CC", "CCK", "Cocos countryList.add(new String[]{Keeling} Islands", "61"});
        countryList.add(new String[]{"CO", "COL", "Colombia", "57"});
        countryList.add(new String[]{"KM", "COM", "Comoros", "269"});
        countryList.add(new String[]{"CD", "COD", "Congo countryList.add(new String[]{DRC}", "242"});
        countryList.add(new String[]{"CG", "COG", "Congo countryList.add(new String[]{Republic}", "682"});
        countryList.add(new String[]{"CK", "COK", "Cook Islands", "506"});
        countryList.add(new String[]{"CR", "CRI", "Costa Rica", "385"});
        countryList.add(new String[]{"HR", "HRV", "Croatia", "53"});
        countryList.add(new String[]{"CU", "CUB", "Cuba", "599"});
        countryList.add(new String[]{"CY", "CYP", "Cyprus", "357"});
        countryList.add(new String[]{"CZ", "CZE", "Czech Republic", "420"});
        countryList.add(new String[]{"DK", "DNK", "Denmark", "45"});
        countryList.add(new String[]{"DJ", "DJI", "Djibouti", "253"});
        countryList.add(new String[]{"DM", "DMA", "Dominica", "767"});
        countryList.add(new String[]{"DO", "DOM", "Dominican Republic", "809"});
        countryList.add(new String[]{"TL", "TLS", "East Timor", "56"});
        countryList.add(new String[]{"EC", "ECU", "Ecuador", "593"});
        countryList.add(new String[]{"EG", "EGY", "Egypt", "20"});
        countryList.add(new String[]{"SV", "SLV", "El Salvador", "503"});
        countryList.add(new String[]{"GQ", "GNQ", "Equatorial Guinea", "240"});
        countryList.add(new String[]{"ER", "ERI", "Eritrea", "291"});
        countryList.add(new String[]{"EE", "EST", "Estonia", "372"});
        countryList.add(new String[]{"ET", "ETH", "Ethiopia", "251"});
        countryList.add(new String[]{"FK", "FLK", "Falkland Islands", "500"});
        countryList.add(new String[]{"FO", "FRO", "Faroe Islands", "298"});
        countryList.add(new String[]{"FJ", "FJI", "Fiji", "679"});
        countryList.add(new String[]{"FI", "FIN", "Finland", "358"});
        countryList.add(new String[]{"FR", "FRA", "France", "33"});
        countryList.add(new String[]{"GF", "GUF", "French Guiana", "596"});
        countryList.add(new String[]{"PF", "PYF", "French Polynesia", "594"});
        countryList.add(new String[]{"TF", "ATF", "French Southern Territories", "689"});
        countryList.add(new String[]{"GA", "GAB", "Gabon", "241"});
        countryList.add(new String[]{"GM", "GMB", "Gambia", "220"});
        countryList.add(new String[]{"GE", "GEO", "Georgia", "995"});
        countryList.add(new String[]{"DE", "DEU", "Germany", "49"});
        countryList.add(new String[]{"GH", "GHA", "Ghana", "233"});
        countryList.add(new String[]{"GI", "GIB", "Gibraltar", "350"});
        countryList.add(new String[]{"GR", "GRC", "Greece", "30"});
        countryList.add(new String[]{"GL", "GRL", "Greenland", "299"});
        countryList.add(new String[]{"GD", "GRD", "Grenada", "473"});
        countryList.add(new String[]{"GP", "GLP", "Guadeloupe", "590"});
        countryList.add(new String[]{"GU", "GUM", "Guam", "671"});
        countryList.add(new String[]{"GT", "GTM", "Guatemala", "502"});
        countryList.add(new String[]{"GN", "GIN", "Guinea", "594"});
        countryList.add(new String[]{"GW", "GNB", "Guinea-Bissau", "245"});
        countryList.add(new String[]{"GY", "GUY", "Guyana", "592"});
        countryList.add(new String[]{"HT", "HTI", "Haiti", "509"});
        countryList.add(new String[]{"HN", "HND", "Honduras", "504"});
        countryList.add(new String[]{"HK", "HKG", "Hong Kong", "852"});
        countryList.add(new String[]{"HU", "HUN", "Hungary", "36"});
        countryList.add(new String[]{"IS", "ISL", "Iceland", "354"});
        countryList.add(new String[]{"IN", "IND", "India", "91"});
        countryList.add(new String[]{"ID", "IDN", "Indonesia", "62"});
        countryList.add(new String[]{"IR", "IRN", "Iran", "98"});
        countryList.add(new String[]{"IQ", "IRQ", "Iraq", "964"});
        countryList.add(new String[]{"IE", "IRL", "Ireland", "353"});
        countryList.add(new String[]{"IM", "IMN", "Isle of Man", "44"});
        countryList.add(new String[]{"IL", "ISR", "Israel", "972"});
        countryList.add(new String[]{"IT", "ITA", "Italy", "39"});
        countryList.add(new String[]{"CI", "CIV", "Ivory Coast", "225"});
        countryList.add(new String[]{"JM", "JAM", "Jamaica", "876"});
        countryList.add(new String[]{"JP", "JPN", "Japan", "81"});
        countryList.add(new String[]{"JO", "JOR", "Jordan", "962"});
        countryList.add(new String[]{"KZ", "KAZ", "Kazakhstan", "7"});
        countryList.add(new String[]{"KE", "KEN", "Kenya", "254"});
        countryList.add(new String[]{"KI", "KIR", "Kiribati", "686"});
        countryList.add(new String[]{"XK", "XKX", "Kosovo", "381"});
        countryList.add(new String[]{"KW", "KWT", "Kuwait", "965"});
        countryList.add(new String[]{"KG", "KGZ", "Kyrgyzstan", "996"});
        countryList.add(new String[]{"LA", "LAO", "Laos", "856"});
        countryList.add(new String[]{"LV", "LVA", "Latvia", "371"});
        countryList.add(new String[]{"LB", "LBN", "Lebanon", "961"});
        countryList.add(new String[]{"LS", "LSO", "Lesotho", "266"});
        countryList.add(new String[]{"LR", "LBR", "Liberia", "231"});
        countryList.add(new String[]{"LY", "LBY", "Libya", "218"});
        countryList.add(new String[]{"LI", "LIE", "Liechtenstein", "423"});
        countryList.add(new String[]{"LT", "LTU", "Lithuania", "370"});
        countryList.add(new String[]{"LU", "LUX", "Luxembourg", "352"});
        countryList.add(new String[]{"MO", "MAC", "Macau", "853"});
        countryList.add(new String[]{"MK", "MKD", "Macedonia", "389"});
        countryList.add(new String[]{"MG", "MDG", "Madagascar", "261"});
        countryList.add(new String[]{"MW", "MWI", "Malawi", "265"});
        countryList.add(new String[]{"MY", "MYS", "Malaysia", "60"});
        countryList.add(new String[]{"MV", "MDV", "Maldives", "960"});
        countryList.add(new String[]{"ML", "MLI", "Mali", "223"});
        countryList.add(new String[]{"MT", "MLT", "Malta", "356"});
        countryList.add(new String[]{"MH", "MHL", "Marshall Islands", "692"});
        countryList.add(new String[]{"MQ", "MTQ", "Martinique", "670"});
        countryList.add(new String[]{"MR", "MRT", "Mauritania", "222"});
        countryList.add(new String[]{"MU", "MUS", "Mauritius", "230"});
        countryList.add(new String[]{"YT", "MYT", "Mayotte", "269"});
        countryList.add(new String[]{"MX", "MEX", "Mexico", "52"});
        countryList.add(new String[]{"FM", "FSM", "Micronesia", "691"});
        countryList.add(new String[]{"MD", "MDA", "Moldova", "373"});
        countryList.add(new String[]{"MC", "MCO", "Monaco", "377"});
        countryList.add(new String[]{"MN", "MNG", "Mongolia", "976"});
        countryList.add(new String[]{"MS", "MSR", "Montserrat", "664"});
        countryList.add(new String[]{"MA", "MAR", "Morocco", "212"});
        countryList.add(new String[]{"MZ", "MOZ", "Mozambique", "258"});
        countryList.add(new String[]{"MM", "MMR", "Myanmar countryList.add(new String[]{Burma}", "95"});
        countryList.add(new String[]{"NA", "NAM", "Namibia", "264"});
        countryList.add(new String[]{"NR", "NRU", "Nauru", "674"});
        countryList.add(new String[]{"NP", "NPL", "Nepal", "977"});
        countryList.add(new String[]{"NL", "NLD", "Netherlands", "31"});
        countryList.add(new String[]{"AN", "ANT", "Netherlands Antilles", "599"});
        countryList.add(new String[]{"NC", "NCL", "New Caledonia", "687"});
        countryList.add(new String[]{"NZ", "NZL", "New Zealand", "64"});
        countryList.add(new String[]{"NI", "NIC", "Nicaragua", "505"});
        countryList.add(new String[]{"NE", "NER", "Niger", "227"});
        countryList.add(new String[]{"NG", "NGA", "Nigeria", "234"});
        countryList.add(new String[]{"NU", "NIU", "Niue", "683"});
        countryList.add(new String[]{"NF", "NFK", "Norfolk Island", "672"});
        countryList.add(new String[]{"KP", "PRK", "North Korea", "850"});
        countryList.add(new String[]{"NO", "NOR", "Norway", "47"});
        countryList.add(new String[]{"OM", "OMN", "Oman", "968"});
        countryList.add(new String[]{"PK", "PAK", "Pakistan", "92"});
        countryList.add(new String[]{"PW", "PLW", "Palau", "680"});
        countryList.add(new String[]{"PA", "PAN", "Panama", "507"});
        countryList.add(new String[]{"PG", "PNG", "Papua New Guinea", "675"});
        countryList.add(new String[]{"PY", "PRY", "Paraguay", "595"});
        countryList.add(new String[]{"PE", "PER", "Peru", "51"});
        countryList.add(new String[]{"PH", "PHL", "Philippines", "63"});
        countryList.add(new String[]{"PN", "PCN", "Pitcairn Islands", "48"});
        countryList.add(new String[]{"PL", "POL", "Poland", "351"});
        countryList.add(new String[]{"PT", "PRT", "Portugal", "239"});
        countryList.add(new String[]{"PR", "PRI", "Puerto Rico", "787"});
        countryList.add(new String[]{"QA", "QAT", "Qatar", "974"});
        countryList.add(new String[]{"RE", "REU", "R", "262"});
        countryList.add(new String[]{"RO", "ROU", "Romania", "40"});
        countryList.add(new String[]{"RU", "RUS", "Russia", "7"});
        countryList.add(new String[]{"RW", "RWA", "Rwanda", "250"});
        countryList.add(new String[]{"SH", "SHN", "Saint Helena", "290"});
        countryList.add(new String[]{"KN", "KNA", "Saint Kitts and Nevis", "869"});
        countryList.add(new String[]{"LC", "LCA", "Saint Lucia", "758"});
        countryList.add(new String[]{"PM", "SPM", "Saint Pierre and Miquelon", "508"});
        countryList.add(new String[]{"VC", "VCT", "Saint Vincent and the Grenadines", "784"});
        countryList.add(new String[]{"SM", "SMR", "San Marino", "378"});
        countryList.add(new String[]{"ST", "STP", "Sao Tome and Principe", "239"});
        countryList.add(new String[]{"SA", "SAU", "Saudi Arabia", "966"});
        countryList.add(new String[]{"SN", "SEN", "Senegal", "221"});
        countryList.add(new String[]{"RS", "SRB", "Serbia", "381"});
        countryList.add(new String[]{"SC", "SYC", "Seychelles", "248"});
        countryList.add(new String[]{"SL", "SLE", "Sierra Leone", "232"});
        countryList.add(new String[]{"SG", "SGP", "Singapore", "65"});
        countryList.add(new String[]{"SK", "SVK", "Slovakia", "421"});
        countryList.add(new String[]{"SI", "SVN", "Slovenia", "386"});
        countryList.add(new String[]{"SB", "SLB", "Solomon Islands", "677"});
        countryList.add(new String[]{"SO", "SOM", "Somalia", "252"});
        countryList.add(new String[]{"ZA", "ZAF", "South Africa", "27"});
        countryList.add(new String[]{"KR", "KOR", "South Korea", "82"});
        countryList.add(new String[]{"ES", "ESP", "Spain", "34"});
        countryList.add(new String[]{"LK", "LKA", "Sri Lanka", "94"});
        countryList.add(new String[]{"SD", "SDN", "Sudan", "249"});
        countryList.add(new String[]{"SR", "SUR", "Suriname", "597"});
        countryList.add(new String[]{"SZ", "SWZ", "Swaziland", "268"});
        countryList.add(new String[]{"SE", "SWE", "Sweden", "46"});
        countryList.add(new String[]{"CH", "CHE", "Switzerland", "41"});
        countryList.add(new String[]{"SY", "SYR", "Syria", "963"});
        countryList.add(new String[]{"TW", "TWN", "Taiwan", "886"});
        countryList.add(new String[]{"TJ", "TJK", "Tajikistan", "992"});
        countryList.add(new String[]{"TZ", "TZA", "Tanzania", "255"});
        countryList.add(new String[]{"TH", "THA", "Thailand", "66"});
        countryList.add(new String[]{"TG", "TGO", "Togo", "228"});
        countryList.add(new String[]{"TK", "TKL", "Tokelau", "690"});
        countryList.add(new String[]{"TO", "TON", "Tonga", "676"});
        countryList.add(new String[]{"TT", "TTO", "Trinidad and Tobago", "868"});
        countryList.add(new String[]{"TN", "TUN", "Tunisia", "216"});
        countryList.add(new String[]{"TR", "TUR", "Turkey", "90"});
        countryList.add(new String[]{"TM", "TKM", "Turkmenistan", "993"});
        countryList.add(new String[]{"TC", "TCA", "Turks and Caicos Islands", "649"});
        countryList.add(new String[]{"TV", "TUV", "Tuvalu", "688"});
        countryList.add(new String[]{"VI", "VIR", "U.S. Virgin Islands", "340"});
        countryList.add(new String[]{"UG", "UGA", "Uganda", "256"});
        countryList.add(new String[]{"UA", "UKR", "Ukraine", "380"});
        countryList.add(new String[]{"AE", "ARE", "United Arab Emirates", "971"});
        countryList.add(new String[]{"GB", "GBR", "United Kingdom", "44"});
        countryList.add(new String[]{"US", "USA", "United States", "1"});
        countryList.add(new String[]{"UY", "URY", "Uruguay", "598"});
        countryList.add(new String[]{"UZ", "UZB", "Uzbekistan", "998"});
        countryList.add(new String[]{"VU", "VUT", "Vanuatu", "678"});
        countryList.add(new String[]{"VA", "VAT", "Vatican City", "39"});
        countryList.add(new String[]{"VE", "VEN", "Venezuela", "58"});
        countryList.add(new String[]{"VN", "VNM", "Vietnam", "84"});
        countryList.add(new String[]{"WF", "WLF", "Wallis and Futuna", "681"});
        countryList.add(new String[]{"YE", "YEM", "Yemen", "967"});
        countryList.add(new String[]{"ZM", "ZMB", "Zambia", "260"});
        countryList.add(new String[]{"ZW", "ZWE", "Zimbabwe", "263"});
        countryList.add(new String[]{"CY", "CYP", "KKTC", "90"});
    }

    private void TR(){

    }
}
